version: '3.8'

services:
  srv-produto:
    container_name: srv-produto
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db-produto
    networks:
      - srv-pedido-network
    volumes:
      - srv-produto-data:/data/produtos
    environment:
      MYSQL_URL: jdbc:mysql://db-produto/produtosdb
      MYSQL_DATABASE: produtosdb
      MYSQL_USER: admin
      MYSQL_PASSWORD: adminpass
    ports:
      - "8086:8086"
    restart: always

  db-produto:
    image: mysql:latest
    container_name: db-produto
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=produtosdb
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=adminpass
    volumes:
      - db-produto-data:/var/lib/postgresql/data
    networks:
      - srv-pedido-network

volumes:
  srv-produto-data:
  db-produto-data:

networks:
  srv-pedido-network:
